### ISSUE TITLE
syntax error, unexpected 'LoopInterface'

### ISSUE THREAD

**Issue by AdeRayendra** [spatie/laravel-short-schedule#12]
hi, I got this error when I tried to run **php artisan short-schedule:run** :

> syntax error, unexpected 'LoopInterface' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)
> 
>   at vendor/spatie/laravel-short-schedule/src/ShortSchedule.php:14

btw I am using laravel 8.6, but it only happens when I try to run it on my production server (centos 7, php 7.4), in my local server (windows 10, php 7.4), it works fine

**Comment by freekmurze** [comment]
Make sure to run PHP 7.4

**Comment by AdeRayendra** [comment]
well, I am using php 7.4, no doubt

**Comment by freekmurze** [comment]
No doubt you're not. Because that is a syntax error that basically screams that you're not on PHP 7.4

Try both these methods: https://freek.dev/1598-how-to-check-which-version-of-php-you-are-running

**Comment by AdeRayendra** [comment]
oh yeah, I am truely sorry, I happened to have multiple php installed, I messed up
