### ISSUE TITLE
The command stops working after a while

### ISSUE THREAD

**Issue by JMauHG** [spatie/laravel-short-schedule#13]
Hello, I have a command running every 30 seconds, it works without problem for a few days, after 3 or 4 days the command stops responding, I have it working with a supervisor, I see the logs and it seems that there are no problems with the supervisor, the command simply It stops working, if I restart my service, the command works again without problems but it breaks again after 3 days, is there a problem with the operating time of the command?

On every code change I reload the php-fpm service so I don't understand what the problem is
I have my command configured this way:

`protected function shortSchedule(ShortSchedule $shortSchedule)
    {
        $shortSchedule->command('command:name')->everySeconds(30);
    }`

**Comment by freekmurze** [comment]
Underneath the hood, this package uses a ReactPHP loop. For my system it seems to work perfectly for days on end.

If you are having troubles with this, best to open up an issue at ReactPHP with details around your system.

**Comment by markeilander** [comment]
> Hello, I have a command running every 30 seconds, it works without problem for a few days, after 3 or 4 days the command stops responding, I have it working with a supervisor, I see the logs and it seems that there are no problems with the supervisor, the command simply It stops working, if I restart my service, the command works again without problems but it breaks again after 3 days, is there a problem with the operating time of the command?
> 
> On every code change I reload the php-fpm service so I don't understand what the problem is
> I have my command configured this way:
> 
> `protected function shortSchedule(ShortSchedule $shortSchedule) { $shortSchedule->command('command:name')->everySeconds(30); }`

Hi There, 

I have the exact same issue.

Have you found a solution?

**Comment by smoetje** [comment]
I have the same issue. I am scheduling a job every 3 seconds doing an api get-request (guzzle) to a plc system from one simple class. When the plc is not responding (not connected), a guzzle exception is handled (logging some data notifying a network-connection issue) and that's it.

It seems after 45 minutes, I get a "too many open files" error in the console and then it shuts down. I could narrow it down to when these exceptions are occurring within the class it's calling. Without this exception, it runs fine without end...

When trying the laravel scheduler (per minute instead) and observing that same process (other id), files are properly opened and closed (during my guzzle-exceptions) and the files-open counter isn't going up. I hoped it worked the similar way as the schedule from laravel but it appears it doesn't...
