### ISSUE TITLE
ShortSchedule does not execute commands

### ISSUE THREAD

**Issue by simplyray** [spatie/laravel-short-schedule#14]
I'm experiencing a weird behavior that ShortSchedule does not execute the actual commands. On my local docker it works fine, on my remote staging server it's working fine as well but on production it just didn't execute the commands.

I've tried to debug the behavior by adding Log entries - the shortSchedule function within the Kernel does get executed; the command itself not. Weirdly there is no error output at all. 

Executing the command directly without supervisor via `php artisan short-schedule:run` does nothing either. 

Kernel.php:
```php
    /**
     * Short schedule for sub minute schedules
     *
     * @param ShortSchedule $shortSchedule
     * @return void
     */
    protected function shortSchedule(ShortSchedule $shortSchedule)
    {
        Log::debug('shortSchedule triggered');
        $shortSchedule->command('test:command')->everySeconds(15)->withoutOverlapping();
    }
```

TestCommand.php:
```php
    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        Log::debug('Test command triggered');
    }
```

All environments are running PHP 7.4 - is there any option within the local PHP configuration that is mandatory to run cronless loops via ReactPHP & ShortSchedule?

**Comment by simplyray** [comment]
Quick update: i think i found the issue! In `PendingShortScheduleCommand`:
```
    public function command(string $artisanCommand):self
    {
        $this->command = "php artisan {$artisanCommand}";

        return $this;
    }
```

On my live server I have multiple PHP versions available via command line; If I trigger the short-schedule via `php7.4 artisan short-schedule:run` it ignores the 7.4 and executes every command with the wrong PHP instance using `php` rather than `php7.4` within the loop.

Would be highly appreciated if that hardcoded `php` could be overwritten via a config setting ... do you need a PR for that?

**Comment by freekmurze** [comment]
Glad you found the problem.

Sure, send a PR with tests and an updated readme 👍
