### ISSUE TITLE
Too much jobs

### ISSUE THREAD

**Issue by gilbertoalbino** [spatie/laravel-short-schedule#17]
Hi, I've created 5 commands and scheduled them in Kernel.php to every 20 seconds, set the crontab and run!
However, my server went down, because it generated 500+ jobs simultaneously, so that it got the server out of memory, freezing everything down:

    protected function shortSchedule(ShortSchedule $schedule)
    { 
        // I've replaced my commands names here!
        $schedule->command('doit:one')->everySeconds(20)->withoutOverlapping();
        $schedule->command('doit:two')->everySeconds(20)->withoutOverlapping();
        $schedule->command('doit:three')->everySeconds(20)->withoutOverlapping();
        $schedule->command('doit:four')->everySeconds(20)->withoutOverlapping();
        $schedule->command('doit:five')->everySeconds(20)->withoutOverlapping();
    }

Any ideas?

**Comment by corvel** [comment]
did you resolve this problem? I have the same issue

**Comment by gilbertoalbino** [comment]
@corvel I still have this issue. I downgraded my project to 'schedule'.
It seems like I need a machine with over 8GB RAM to run short-schedule on production.
My development machine is 32GB, I couldn't perceive this at first,
but at the moment I'm writing this, running 5 commands requires 10GB of RAM.
I might be missing something here, but this tool shouldn't consume all that memory.
I am running PHP 7.4.12.

**Comment by HaoLVb** [comment]
did you resolve this? I have the same issue

**Comment by HaoLVb** [comment]
did you resolve this? I have the same issue

**Comment by chrismackie28** [comment]
Also having this issue, almost mazing out a 16GB 8xCPU server while running 1 command every 5 seconds.

**Comment by Mzril** [comment]
@gilbertoalbino 
> Hi, I've created 5 commands and scheduled them in Kernel.php to every 20 seconds, **set the crontab** and run!

Just to be clear, you're calling the short-schedule:run function inside a cron process?

**Comment by gilbertoalbino** [comment]
> @gilbertoalbino
> 
> > Hi, I've created 5 commands and scheduled them in Kernel.php to every 20 seconds, **set the crontab** and run!
> 
> Just to be clear, you're calling the short-schedule:run function inside a cron process?

I was running with Supervisor.

**Comment by freekmurze** [comment]
I'm not seeing these problems on my apps. I would welcome a PR that fixes this problem.

A think that might be worth to PR is a maximum lifetime of the short schedule. After X minutes it could terminate itself. Something like Supervisor would bring it back up. This way any memory leaks inside of a command could be mitigated.

**Comment by jimping** [comment]
@gilbertoalbino I think you misunderstood the way this package works. The command is just like an own daemon like laravel horizon. It does not exit like the default scheduler. So crontab is they wrong place to run the scheduler as you will have multiple instances of the short schedule doing it’s job. Just use supervisor to keep it alive :)
