### ISSUE TITLE
Missing functionality runInBackground()

### ISSUE THREAD

**Issue by Tklaversma** [spatie/laravel-short-schedule#18]
By default, multiple commands scheduled at the same time will execute **sequentially**. If I would like to run multiple short scheduled commands simultaneously, I cannot, since the functionality ```->runInBackground()``` is not available for short scheduler.

Can this be added?

**Comment by freekmurze** [comment]
I don't need this, some I'm not going to invest my time. Feel free to submit a PR with tests and updated docs that adds this. I'll merge it in if the code to achieve this is simple enough.
