### ISSUE TITLE
Scheduling Queued Jobs

### ISSUE THREAD

**Issue by wlepinski** [spatie/laravel-short-schedule#2]
Is it possible to schedule a job like https://laravel.com/docs/7.x/scheduling#scheduling-queued-jobs on the native scheduler?

**Comment by freekmurze** [comment]
At the moment that feature isn't support, but I do welcome a PR with tests and updated documentation that adds it.

**Comment by freekmurze** [comment]
Going to close it as I don't want to only keep issues open for actual problems, not feature requests.
