### ISSUE TITLE
PHP8 Support

### ISSUE THREAD

**Issue by tpaksu** [spatie/laravel-short-schedule#24]
Hello,

Can you add PHP8 to the composer.json required PHP version list? I've recently updated my PHP version but this package won't allow me to update my composer dependencies :) I don't know if you're going to refactor the code to use the new features coming from PHP8, but an updated composer.json only release will be the best. 

Thank you!

**Comment by freekmurze** [comment]
I you need this quick, send a PR, make sure the tests run on PHP 8 as well.

**Comment by tpaksu** [comment]
Yep, will do.

**Comment by tpaksu** [comment]
I prepared everything but couldn't make the test case work for "prefer-lowest" because mockery/mockery has this issue which prevents orchestral/testbench to work correctly in PHP8. 

The issue for mockery/mockery : 
https://github.com/mockery/mockery/issues/1071

The issue for orchestral/testbench : 
https://github.com/orchestral/testbench-core/issues/51

The github action page for the update: 
https://github.com/tpaksu/laravel-short-schedule/actions/runs/441091738

Doesn't seem like a showstopper? Once they fix that the actions will automatically turn to green (Hope so). 

How should we proceed? (I'll revert the `fail-fast` flag before the PR)

**Comment by freekmurze** [comment]
> I prepared everything but couldn't make the test case work for "prefer-lowest" because mockery/mockery 

I think you could solve it by requiring the latest version of mockery.

If things could be made easier by dropping support for older Laravel versions, feel free to do son.

**Comment by tpaksu** [comment]
Ok, that did the trick. Thank you 👍🏼  Reverting the fail-fast back to false and preparing a PR. 

Here are the latest test results:
https://github.com/tpaksu/laravel-short-schedule/actions/runs/441144786
