### ISSUE TITLE
There are no commands defined in the "short-schedule" namespace

### ISSUE THREAD

**Issue by nemo3000** [spatie/laravel-short-schedule#48]
I'm using php 7.4, laravel 5.8 and laravel-short-schedule 1.1.
When I run php artisan short-schedule:run I have this message:
There are no commands defined in the "short-schedule" namespace.
I have already created a artisan command and that command work perfect.

**Comment by freekmurze** [comment]
This package is not compatible with Laravel 5.8. See: https://github.com/spatie/laravel-short-schedule/blob/3578fcdc2144c739897a2251beb2da8f841eff54/composer.json#L20

**Comment by nemo3000** [comment]
illuminate/cache 7 and 8 are required only from version 1.2 I'm using old version where is not required.

**Comment by nemo3000** [comment]
I found problem, was a wrong permision on a file, nothing of related to this component.
Now work fine with laravel 5.8!!
Thank you

**Comment by vikasvyas47** [comment]
> I found problem, was a wrong permision on a file, nothing of related to this component. Now work fine with laravel 5.8!! Thank you

can you please help how you solve this problem like where you give permission because i am facing same problem
