### ISSUE TITLE
option for onOneServer

### ISSUE THREAD

**Issue by lionslair** [spatie/laravel-short-schedule#6]
I was not sure where else to ask this. Is there a technical reason why onOneServer option does not exist? Close to all the other options in the native schedule methods are in this package except for onOneServer. 

Is this due to a limitation with react-loop?

**Comment by freekmurze** [comment]
I didn't need `onOneServer` myself, so I didn't invest time in it.

If you need it, feel free to submit a PR.

**Comment by lionslair** [comment]
Is there some technical limitation or complication to it though that I need to solve or simply you not need it?

**Comment by freekmurze** [comment]
I haven't taken a look at the problem, so I don't know if there are any technical hurdles to take.
