### ISSUE TITLE
supervisor doesn't fire

### ISSUE THREAD

**Issue by fatihtoprak** [spatie/laravel-short-schedule#7]
hello, i m using supervisor, it doesn't fire my console command like; 

`command=php artisan short-schedule:run --no-interaction`

but the process works without supervisor. 

the point another commands still works perfectly on supervisor too.

`command=php artisan supervisor-test --no-interaction`

**Comment by alperdem1r** [comment]
I've the same problem. I tried placing it in a while loop in supervisor config. This was not helpful either. Can someone who can run this with supervisor share their config?

Thanks.

**Comment by sirBobz** [comment]
Aaah looks like I'm not the only having a problem running it with supervisor.

I agree, anyone who has been successful running this with supervisor, share your configs.

**Comment by maryleloisa** [comment]
Please add me too to the "having trouble with supervisor" list ...

**Comment by freekmurze** [comment]
I currently don't have time to look into this, but I'd accept a PR that fixes this.

**Comment by lionslair** [comment]
I seem to have the same issue. The process is running but none of the tasks within appear to be doing anything

**Comment by lionslair** [comment]
Been debugging all morning

Adding this
`     if (Str::startsWith($commandString, 'php artisan')) {
            Artisan::call(Str::after($commandString, 'php artisan'));
        }`

inside of 

```
private function processCommand(): void
    {
        $commandString = $this->pendingShortScheduleCommand->command;
        logger('command: ' . $commandString);
        if (Str::startsWith($commandString, 'php artisan')) {
            Artisan::call(Str::after($commandString, 'php artisan'));
        }
        $this->process = Process::fromShellCommandline($commandString);

        event(new ShortScheduledTaskStarting($commandString, $this->process));
        $this->process->start();
        event(new ShortScheduledTaskStarted($commandString, $this->process));
    }
```

makes it work. Something is not right with the way `Process::fromShellCommandline($commandString);` calls 
 php artisan <artsian-command>

**Comment by lionslair** [comment]
Ok I have worked it out. when you run this in the CLI it knows what the current working directory is. eg

`/var/www/q  `

when it runs from supervisor it has eg

`/etc/supervisor.d/conf`

So we just need to pass the base_path when using using the command() method opposed to the exec method. I will create a PR shortly.

**Comment by freekmurze** [comment]
We'll continue the conversation in #9

**Comment by fatihtoprak** [comment]
All done. thanks
