### ISSUE TITLE
Deprecation warning (Carbon)

### ISSUE THREAD

**Issue by maciek-szn** [spatie/laravel-short-schedule#76]
Running `short-schedule:run` in the latest version (1.5.1) gives a following warning:

`Since 2.61.0, it's deprecated to compare a date to null, meaning of such comparison is ambiguous and will no longer be possible in 3.0.0, you should explicitly pass 'now' or make an other check to eliminate null values. in [...]\vendor\nesbot\carbon\src\Carbon\Traits\Comparison.php on line 1115`

**Comment by freekmurze** [comment]
Could you post the entire stacktrace? Or, even better, submit a PR that fixes this?

**Comment by maciek-szn** [comment]
I'm closing this as it seems that the issue is in Laravel itself. Sorry for bothering you.
